
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
include: ['.htaccess']

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

future: true

# Site settings
name: "Salud-Zen, Escuela de Luz y Consciencia"
description: ""
title: Salud-Zen
subtitle: "Escuela de Luz y Consciencia"
##url: "http://salud-zen.sytechcom.com/" # the base hostname & protocol for your site
#url: "https://salud-zen.000webhostapp.com" # the base hostname & protocol for your site
#url: "https://besaru.github.io/saludzen/"
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
#url: 'http://www.salud-zen.com'
baseurl: ""
url: "https://besaru.github.io"
#baseurl: '/saludzen'
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-109788432-1"
